version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - elvispt
  ignore:
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.9
    - 2.8.2
  - dependency-name: algolia/scout-extended
    versions:
    - 1.14.0
    - 1.16.0
  - dependency-name: phpseclib/phpseclib
    versions:
    - 3.0.7
  - dependency-name: laravel/framework
    versions:
    - 7.30.2
    - 7.30.4
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
